### ISSUE TITLE
Images converted into integers - why?

### ISSUE THREAD

**Issue by KristinaUlicna** [alan-turing-institute/grace#148]
A few instances:

https://github.com/alan-turing-institute/grace/blob/4cafa2824c4b8fe790a7ac5546e5bea57414ad3d/examples/show_data.py#L24

https://github.com/alan-turing-institute/grace/blob/4cafa2824c4b8fe790a7ac5546e5bea57414ad3d/grace/io/image_dataset.py#L102

https://github.com/alan-turing-institute/grace/blob/4cafa2824c4b8fe790a7ac5546e5bea57414ad3d/grace/io/image_dataset.py#L119

What's the rationale here? @quantumjot @mooniean ?

**Comment by KristinaUlicna** [comment]
@chris-soelistyo FYI, this issue is causing problems when reading / training on the simulated data - but commenting the `astype(int)` out doesn't resolve it.

**Comment by chris-soelistyo** [comment]
In previous versions of the code, the images were being converted in order to deal with situations where the `mrc` files are stored as `np.uint16`, which is unconvertible to a `torch.Tensor`, hence `.astype(int)` was being used to convert to `np.int64, which _could_ be converted. In the current version, however, this feature has been removed in favour of simply converting to `np.float32` before conversion to a `torch.Tensor`, seeing as `np.float32` is the datatype required for input to the models anyway.
